export CONFIG_QNUX_VERSION = 1.0.0
export CONFIG_TARGET = x86_64-qnux-linux-gnu
export CONFIG_LINUX_ARCH = x86_64
export CONFIG_GCC_ARCH = x86-64
export CONFIG_STRIP_AND_DELETE_DOCS = 1
export CONFIG_HOSTNAME = qnux
export CONFIG_ROOT_PASSWD = qnux